# Generated by Django 4.2.3 on 2023-08-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_student_is_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
