# Generated by Django 4.2.3 on 2023-11-08 11:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/leader/image')),
                ('position', models.CharField(max_length=128, verbose_name='Position')),
                ('position_uz', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_en', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('position_ru', models.CharField(max_length=128, null=True, verbose_name='Position')),
                ('detail_link', models.TextField()),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Leaders',
            },
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('theme', models.CharField(max_length=128)),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='upload/path/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'docx', 'pptx'])])),
                ('type_application', models.CharField(choices=[(None, 'Tanlang'), ('tk', 'taklif'), ('shk', 'shikoyat'), ('apl', 'apellatsiya')], max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('is_viewed', models.BooleanField(default=False)),
                ('is_answered', models.BooleanField(default=False)),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leader')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('student_id', models.CharField(max_length=15)),
                ('leader', models.CharField(max_length=128)),
                ('appeal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.appeal')),
            ],
        ),
    ]
