# Generated by Django 4.2.3 on 2023-07-21 09:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/leader/image')),
                ('leader', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=15)),
                ('faculty', models.CharField(max_length=60)),
                ('eduForm', models.CharField(max_length=20)),
                ('specialty', models.CharField(max_length=60)),
                ('group', models.CharField(max_length=20)),
                ('full_name', models.CharField(max_length=80)),
                ('phone', models.CharField(max_length=13)),
                ('message', models.TextField()),
                ('file_upload', models.FileField(blank=True, null=True, upload_to='upload/path/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'pdf', 'docx', 'pptx'])])),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.leader')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('student_id', models.CharField(max_length=15)),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.leader')),
            ],
        ),
    ]
