# Generated by Django 4.2.3 on 2024-08-08 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='media/rentalHouse/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.xls', '.xlsx'])])),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/rentalHouse/images')),
            ],
        ),
    ]
