# Generated by Django 4.2.3 on 2023-07-24 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='eduForm',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='group',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='specialty',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='student_id',
        ),
        migrations.AddField(
            model_name='appeal',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
