# Generated by Django 4.2.3 on 2023-07-24 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_appeal_eduform_remove_appeal_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='leader',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
