# Generated by Django 4.2.3 on 2024-08-08 08:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rentalhouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalhouse',
            name='file',
            field=models.FileField(upload_to='media/rentalHouse/files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'xls', 'xlsx'])]),
        ),
    ]
