# Generated by Django 4.2.3 on 2023-07-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_answer_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='theme',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appeal',
            name='type_application',
            field=models.CharField(choices=[('taklif', 'taklif'), ('shikoyat', 'shikoyat'), ('apellatsiya', 'apellatsiya')], default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leader',
            name='position',
            field=models.CharField(default=2, max_length=128),
            preserve_default=False,
        ),
    ]
