# Generated by Django 4.2.3 on 2023-08-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appeal_theme_appeal_type_application_leader_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appeal',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='type_application',
            field=models.CharField(choices=[(None, 'Tanlang'), ('taklif', 'taklif'), ('shikoyat', 'shikoyat'), ('apellatsiya', 'apellatsiya')], max_length=15),
        ),
    ]
