# Generated by Django 4.2.3 on 2023-08-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_leader_detail_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='message_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='theme_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='theme_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='appeal',
            name='theme_uz',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_en',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_ru',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='leader',
            name='position_uz',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
