# Generated by Django 4.2.3 on 2023-08-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_answer_message_en_answer_message_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leader',
            options={'verbose_name_plural': 'Leaders'},
        ),
        migrations.AlterField(
            model_name='leader',
            name='position',
            field=models.CharField(max_length=128, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Position'),
        ),
        migrations.AlterField(
            model_name='leader',
            name='position_uz',
            field=models.CharField(max_length=128, null=True, verbose_name='Position'),
        ),
    ]
