# Generated by Django 4.2.3 on 2023-08-11 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_leader_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_en',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_ru',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='message_uz',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='theme_en',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='theme_ru',
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='theme_uz',
        ),
    ]
