# Generated by Django 4.2.3 on 2023-08-11 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_appeal_is_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appeal',
            old_name='is_viewed',
            new_name='is_seen',
        ),
    ]
