# Generated by Django 4.2.3 on 2023-08-11 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_rename_is_viewed_appeal_is_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appeal',
            name='is_seen',
        ),
    ]
