# Generated by Django 4.2.3 on 2023-08-18 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_appeal_is_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='appeal',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='main.appeal'),
            preserve_default=False,
        ),
    ]
