# Generated by Django 4.2.3 on 2023-09-12 08:43

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_answer_appeal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='message',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='appeal',
            name='type_application',
            field=models.CharField(choices=[(None, 'Tanlang'), ('tk', 'taklif'), ('shk', 'shikoyat'), ('apl', 'apellatsiya')], max_length=15),
        ),
    ]
