# Generated by Django 4.2.3 on 2023-09-19 06:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_appeal_type_application_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
